//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long CustAID { get; set; }
        public string CustID { get; set; }
        public string CustName { get; set; }
        public string CustFatherName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> comcod { get; set; }
        public string ContPer1 { get; set; }
        public string ContPer2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> eID { get; set; }
        public string CHNo { get; set; }
        public Nullable<System.DateTime> CHDate { get; set; }
        public string MRNo { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<double> tAmnt { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UserID { get; set; }
        public string Profession { get; set; }
        public string Org { get; set; }
        public string Desg { get; set; }
        public string CustSex { get; set; }
        public string IdentityType { get; set; }
        public string IdentityNo { get; set; }
        public string CustRef { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DOBT { get; set; }
        public string CustType { get; set; }
        public string CustArea { get; set; }
        public string CustAge { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
