//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int EID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string eName { get; set; }
        public string eNameBangla { get; set; }
        public string EDesc { get; set; }
        public string EDescBangla { get; set; }
        public string EntityType { get; set; }
        public string ParentEntity { get; set; }
        public string Showroomtype { get; set; }
        public Nullable<int> CommissionGet { get; set; }
        public Nullable<int> SalesOrShowroom { get; set; }
        public Nullable<int> ActiveDeactive { get; set; }
        public Nullable<int> GroupSL { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> sFlag { get; set; }
        public Nullable<int> EnableSalesSheet { get; set; }
        public Nullable<decimal> SecurityMoney { get; set; }
        public Nullable<decimal> DepositedUpTo0809 { get; set; }
        public string EntityCode { get; set; }
        public Nullable<int> NoTr { get; set; }
        public Nullable<int> DP_Inactive { get; set; }
        public string ContactPerson { get; set; }
        public string Desg { get; set; }
        public string Status { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> InDhk { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<int> CorporateSale { get; set; }
        public Nullable<int> iTagStock { get; set; }
        public Nullable<int> SalesCenterType { get; set; }
        public string MapLink { get; set; }
        public Nullable<int> pEID { get; set; }
        public string ReqMailTo { get; set; }
    }
}
