//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRSRMaster
    {
        public string comcod { get; set; }
        public int MRSRMID { get; set; }
        public string MRSRCode { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<short> TrType { get; set; }
        public string POCode { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> SID { get; set; }
        public string LCNO { get; set; }
        public string InvoiceNO { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> InSource { get; set; }
        public Nullable<int> OutSource { get; set; }
        public string ACC { get; set; }
        public string PN { get; set; }
        public string FC { get; set; }
        public string LOC { get; set; }
        public string VehID { get; set; }
        public string JCN { get; set; }
        public string ReqBy { get; set; }
        public string Authorby { get; set; }
        public Nullable<System.DateTime> RcvChDate { get; set; }
        public string RcvChNo { get; set; }
        public string AppBy { get; set; }
        public string Issby { get; set; }
        public string IssueTo { get; set; }
        public string RecBy { get; set; }
        public string Customer { get; set; }
        public string ReportID { get; set; }
        public Nullable<System.DateTime> chaDate { get; set; }
        public string Tag { get; set; }
        public string JobNo { get; set; }
        public string Remarks { get; set; }
        public string Department { get; set; }
        public string ProdCode { get; set; }
        public string BLNo { get; set; }
        public string PayMode { get; set; }
        public string BankName { get; set; }
        public string ChequeNmbr { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> NetSalesAmnt { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipFrom { get; set; }
        public Nullable<int> RefStatus { get; set; }
        public string RefCHNo { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> HelperID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string CarrierType { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string CarryNo { get; set; }
        public Nullable<int> CustAID { get; set; }
        public string MRNO { get; set; }
        public Nullable<decimal> PayAmnt { get; set; }
        public Nullable<decimal> DueAmnt { get; set; }
        public string PayType { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeIssueDate { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<decimal> CashAmnt { get; set; }
        public Nullable<decimal> CardAmnt1 { get; set; }
        public Nullable<decimal> CardAmnt2 { get; set; }
        public string CardNo1 { get; set; }
        public string CardNo2 { get; set; }
        public string CardType1 { get; set; }
        public string CardType2 { get; set; }
        public string Bank1 { get; set; }
        public string Bank2 { get; set; }
        public string SecurityCode2 { get; set; }
        public string AppovalCode1 { get; set; }
        public string AppovalCode2 { get; set; }
        public string TermsCondition { get; set; }
        public Nullable<bool> SalesTypeHP { get; set; }
        public Nullable<bool> HPStatus { get; set; }
        public Nullable<bool> OnLineSales { get; set; }
        public Nullable<int> DeliveryFrom { get; set; }
        public Nullable<int> EditTag { get; set; }
        public Nullable<int> DelStatus { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string ROSDetails { get; set; }
        public Nullable<int> DAID { get; set; }
        public string SourceOfInfo { get; set; }
        public Nullable<bool> AdvanceSales { get; set; }
    }
}
