//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveProductSerial
    {
        public int AID { get; set; }
        public string IncomingNo { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string RModel { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string OriginalSerial { get; set; }
        public string NewSerial { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
