//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirmentDetail
    {
        public int ReqDAID { get; set; }
        public Nullable<int> ReqAID { get; set; }
        public string ReqNo { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> ReqQty { get; set; }
        public string ProdRemarks { get; set; }
    }
}
