//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftUser
    {
        public int ID { get; set; }
        public Nullable<int> RolesId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Designation { get; set; }
        public string Passward { get; set; }
        public string WebAccess { get; set; }
        public string WebAccessType { get; set; }
        public string UserType { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> EID { get; set; }
        public string eName { get; set; }
        public string BranchCode { get; set; }
        public string ChngPass { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> iTagStock { get; set; }
        public Nullable<int> iSpinWin { get; set; }
        public Nullable<int> iVatUser { get; set; }
    }
}
