//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrierInfo
    {
        public int CarrierID { get; set; }
        public string CarrierCode { get; set; }
        public string CarrierName { get; set; }
        public string CAdd { get; set; }
        public string CContact { get; set; }
        public string CEmail { get; set; }
    }
}
