//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDistThana
    {
        public int TDID { get; set; }
        public string Dist { get; set; }
        public string Thana { get; set; }
        public string Dist_Bangla { get; set; }
        public string Div_ { get; set; }
        public Nullable<int> CountryID { get; set; }
    }
}
