//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMenu
    {
        public int MenuId { get; set; }
        public string MenuCode { get; set; }
        public string Title { get; set; }
        public string MenuTitle { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
    }
}
