//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSMSRead
    {
        public long RMID { get; set; }
        public string ContactNo { get; set; }
        public string TextSMS { get; set; }
        public Nullable<System.DateTime> smsDate { get; set; }
        public Nullable<int> SMSRead { get; set; }
    }
}
