//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStoreInfo
    {
        public int StoreAID { get; set; }
        public string SCode { get; set; }
        public string SName { get; set; }
        public string SAddress { get; set; }
        public string SContact { get; set; }
    }
}
