//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTagPromocode
    {
        public int CustAID { get; set; }
        public string CustName { get; set; }
        public string CustAdd { get; set; }
        public string CustMobile { get; set; }
        public string CustDOB { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProdCode { get; set; }
        public string Model { get; set; }
        public string Dis_Gift { get; set; }
        public Nullable<double> DisPer { get; set; }
        public string ChNo { get; set; }
        public Nullable<int> sTag { get; set; }
        public string DisText { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryTime { get; set; }
        public Nullable<int> EID { get; set; }
        public string DisCode { get; set; }
        public Nullable<int> DisCodeTag { get; set; }
        public Nullable<System.DateTime> EntryDate1 { get; set; }
        public Nullable<int> NoOfTag { get; set; }
        public string path { get; set; }
    }
}
