//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTargetYearly
    {
        public int TID { get; set; }
        public string TYear { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<int> EntitySerial { get; set; }
        public string EntityName { get; set; }
        public Nullable<decimal> TAmount { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
