//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTC_Customer
    {
        public long CTCAID { get; set; }
        public Nullable<long> MRSRMID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> tcAID { get; set; }
        public string TCText { get; set; }
    }
}
