//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVehicleInfo
    {
        public int VAID { get; set; }
        public string VRegNo { get; set; }
        public string ChassisNo { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string TypeOfV { get; set; }
        public string Manufacturer { get; set; }
        public string ManfCountry { get; set; }
        public string Organization { get; set; }
        public string Remarks { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
