//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVendorInfo
    {
        public int VAID { get; set; }
        public string VName { get; set; }
        public string VContact { get; set; }
        public string VAddress { get; set; }
        public string VPhoto { get; set; }
        public string VNID { get; set; }
        public string VRef { get; set; }
        public string VType { get; set; }
        public Nullable<bool> status { get; set; }
        public string VNIDNo { get; set; }
        public string VContact2 { get; set; }
        public string UserID { get; set; }
        public string PModel { get; set; }
        public string NickName { get; set; }
    }
}
