//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Search_Sales
    {
        public string OutSource { get; set; }
        public string MRSRCode { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<short> TrType { get; set; }
        public string Model { get; set; }
        public string GroupName { get; set; }
        public Nullable<double> Qty { get; set; }
        public string InSource { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalAmnt { get; set; }
        public Nullable<decimal> DiscountAmnt { get; set; }
        public Nullable<decimal> NetAmnt { get; set; }
        public string SLNO { get; set; }
    }
}
