//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Sales_BILL
    {
        public Nullable<short> TrType { get; set; }
        public string MRSRCode { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string PayMode { get; set; }
        public string BankName { get; set; }
        public string ChequeNmbr { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public string ProdName { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string GroupName { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<decimal> TotalAmnt { get; set; }
        public string SLNO { get; set; }
        public Nullable<decimal> DiscountAmnt { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> NetAmnt { get; set; }
        public Nullable<decimal> WithAdjAmnt { get; set; }
        public Nullable<decimal> CampDisAmnt { get; set; }
        public string DisRef { get; set; }
        public string DisCode { get; set; }
        public string ProdRemarks { get; set; }
        public int EID { get; set; }
        public string eName { get; set; }
        public string EDesc { get; set; }
        public string EntityType { get; set; }
        public string ModelSerial { get; set; }
        public Nullable<decimal> PayAmnt { get; set; }
        public Nullable<decimal> DueAmnt { get; set; }
        public Nullable<System.DateTime> ChequeIssueDate { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<decimal> CashAmnt { get; set; }
        public Nullable<decimal> CardAmnt1 { get; set; }
        public Nullable<decimal> CardAmnt2 { get; set; }
        public string CardNo1 { get; set; }
        public string CardNo2 { get; set; }
        public string CardType1 { get; set; }
        public string CardType2 { get; set; }
        public string Bank1 { get; set; }
        public string Bank2 { get; set; }
        public string SecurityCode2 { get; set; }
        public string AppovalCode1 { get; set; }
        public string AppovalCode2 { get; set; }
        public string Remarks { get; set; }
        public string TermsCondition { get; set; }
        public Nullable<int> DelFromID { get; set; }
        public string DelFromName { get; set; }
        public string DelFromAdd { get; set; }
        public Nullable<bool> OnLineSales { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<double> BLIPAmnt { get; set; }
        public Nullable<double> IncentiveAmnt { get; set; }
        public string IncentiveType { get; set; }
        public Nullable<double> CustShowPrice { get; set; }
        public Nullable<bool> GetIncentive { get; set; }
        public string RefCHNo { get; set; }
        public string POCode { get; set; }
        public Nullable<int> EarnedVoucherPoint { get; set; }
        public Nullable<int> EarnedVoucherAmt { get; set; }
    }
}
